# Name
REPO_NAME           ?= Korean Empty Set

# File name of *.grf, *.tar and so on
BASE_FILENAME       ?= ko_empty_set

# Version
VERSION             ?= $(shell ./findversion.sh)
RECENT_UPDATED      ?= $(shell date +"%Y.%m.%d")
REPO_BRANCH_VERSION ?= 0

# Author's information
AUTHOR_WEBSITE      ?= https://domain.com
AUTHOR_EMAIL        ?= your_email@address.com

# If needed, declare the minimum NML requirements
REQUIRED_NML_BRANCH  = 0.4
# MIN_NML_REVISION   = 0
