name: "[오브젝트추가]"
description: 새로운 오브젝트를 추가하고 싶으십니까?
title: "[오브젝트 추가]"
labels: "Add objects"
body:
  - type: markdown
    attributes:
      value: |
        새로운 오브젝트을 추가해주셔서 감사합니다!
  - type: textarea
    attributes:
      label: 필수 스프라이트
      description: 필수 스프라이트를 올려주세요.
  - type: textarea
    attributes:
      label: 32bpp 스프라이트
      description: 32bpp 스프라이트를 올려주세요.
      placeholder: '주의점. 기본스프라이트가 없으면 본 32bpp는 적용되지 않는것이 기본입니다. 신규 오브젝트시 꼭 기본 스프라이트를 우선적으로 작업해주세요.'
  - type: textarea
    attributes:
      label: 설명
      description: 설명사항을 적어주세요.  
  - type: input
    attributes:
      label: GRF내 이름 한국어
      description: GRF내 이름을 한국어로 적어주세요.
      placeholder: 오브젝트이름
    validations:
      required: true
  - type: input
    attributes:
      label: GRF내 이름 영문
      description: GRF내 이름을 영어로 적어주세요.
      placeholder: Object Name
    validations:
      required: true
  - type: input
    attributes:
      label: 도입년도
      description: 등장년도를 적어주세요.
      placeholder: '2023'
    validations:
      required: true