name: "[추가사항]"
description: 새로운 열차를 추가하고 싶으십니까?
title: "[열차추가]"
labels: "Add train"
body:
  - type: markdown
    attributes:
      value: |
        새로운 차량을 추가해주셔서 감사합니다!
  - type: textarea
    attributes:
      label: 스프라이트
      description: 스프라이트를 올려주세요. 기본적으로 32bpp를 지원하도록 하여 적용하고 있습니다. 크로마키부분만을 투명상태로 적용해주세요.
  - type: textarea
    attributes:
      label: 깃허브 자료실 파일명
      description: 깃허브 자료실내 파일명을 명시해주세요. 이슈적용시 혼란을 막기 위함입니다. 번거롭더라도 협조부탁드립니다.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: '실존 & 가상열차'
      description: '실존 & 가상여부를 체크해주세요.'
      options:
      - label: '실존차량'
      - label: '가상열차'
  - type: checkboxes
    attributes:
      label: 편성방식
      description: 편성방식을 선택해주세요.
      options:
      - label: '고정편성'
      - label: '단일구성 (객화차 & 단일 기관차)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 설명
      description: 설명사항을 적어주세요.  
  - type: input
    attributes:
      label: GRF내 열차 이름 한국어
      description: GRF내 열차 이름을 한국어로 적어주세요.
      placeholder: 열차이름
    validations:
      required: true
  - type: input
    attributes:
      label: GRF내 열차 이름 영문
      description: GRF내 열차 이름을 영어로 적어주세요.
      placeholder: Train Name
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 열차속도
      description: 열차의 속도를 정해주세요 게임내 속도 매겨변수를 정의하는 것입니다.
      options:
      - label: '지하철/통근열차 100 ~ 151km/h'
      - label: '일반열차 151 ~ 181km/h'
      - label: '준고속열차 181 ~ 260km/h'
      - label: '고속열차 300 ~ 380km/h'
      - label: '준초고속열차 430 ~ 600km/h'
      - label: '초고속열차 600km/h'
    validations:
      required: true
  - type: input
    attributes:
      label: 도입년도
      description: 등장년도를 적어주세요.
      placeholder: '2023'
    validations:
      required: true
  - type: input
    attributes:
      label: 전체 편성수
      description: 열차 편성을 적어주세요.
      placeholder: '4량/6량'
    validations:
      required: true
  - type: input
    attributes:
      label: 객차당 수송량
      description: '열차 수송량을 계산하여 적어주세요. [계산식] 전체 수송량/열차편성수=?명 (반올림 및 정수값 세팅)'
      placeholder: '121명'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 편성구조
      description: 열차 편성 구조를 스프라이트 이름과 함께 직관적으로 알려주세요.
      placeholder: '앞- N량 객차 - 뒤 순으로 명시.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 적용스팩 세부사항
      description: 적용스팩에 대한 추가적 사항을 상세히 적어주세요.