name: "[버그사항]"
description: DTS에서 버그사항을 찾으셨습니까?
title: "[버그]"
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        버그사항 접수해주셔서 감사합니다.!
  - type: input
    attributes:
      label: 열차이름
      description: 게임에서 나오는 해당 열차 이름을 적어주세요.
      placeholder: '[DTS/N량] 열차이름'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 버그사항
      description: 문제가 발생한 버그사항. 필요시 스샷 첨부
    validations:
      required: true
  - type: textarea
    attributes:
      label: 개선점
      description: 개선될 사항을 알려주세요.
    validations:
      required: true