name: "[버그사항]"
description: Found a bug in OpenTTD?
title: "[버그]"
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        버그사항 접수해주셔서 감사합니다.!
  - type: textarea
    id: bug
    attributes:
      label: bug
      description: 문제가 발생한 버그사항.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: Describe in a few words what actually happens.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: As detailed as possible, please tell us how we can reproduce this. Feel free to attach a savegame (zip it first) to make it more clear.
      placeholder: |
        1. Loaded the attached savegame.
        2. Click on the button left of that other icon.
        3. The window doesn't open.
    validations:
      required: true