name: "[버그사항]"
description: Found a bug in OpenTTD?
title: "[버그]"
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        버그사항 접수해주셔서 감사합니다.!
  - type: textarea
    id: Bugs
    attributes:
      label: bugs
      description: 문제가 발생한 버그사항. 필요시 스샷 첨부
    validations:
      required: true
  - type: textarea
    id: Improve
    attributes:
      label: Improve
      description: 개선될 사항을 알려주세요.
    validations:
      required: true