name: "[버그사항] 오브젝트 "
description: DTS중 오브젝트에 버그사항을 찾으셨습니까?
title: "[버그]"
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        버그사항 접수해주셔서 감사합니다.!
  - type: dropdown
    attributes:
      label: 오브젝트 선택
      description: 오브젝트를 선택해주세요.
      options:
        - '[DTS] 콘크리트 차막이'
        - '[DTS] 자갈 차막이'
        - '[DTS] 표지판 차막이'
        - '[DTS] 역전 CU 편의점'
        - '[DTS] 역전 GS25 편의점'
        - '[DTS] 역전 스토리웨이 편의점'
        - '[DTS] 태극기'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 버그사항
      description: 문제가 발생한 버그사항. 필요시 스샷 첨부
    validations:
      required: true
  - type: textarea
    attributes:
      label: 개선점
      description: 개선될 사항을 알려주세요.
    validations:
      required: true