name: "[버그사항] 일본형 "
description: DTS중 일본형 열차에 버그사항을 찾으셨습니까?
title: "[버그]"
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        버그사항 접수해주셔서 감사합니다.!
  - type: dropdown
    attributes:
      label: 일본형 열차 선택
      description: 일본형 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/4량] 니시테츠 1000형'
        - '[DTS/6량] 니시테츠 2000형'
        - '[DTS] 니시테츠 3000형'
        - '[DTS] 니시테츠 5000형'
        - '[DTS] 니시테츠 6000형'
        - '[DTS/2량] 니시테츠 7000형'
        - '[DTS/6량] 니시테츠 8000형'
        - '[DTS] 니시테츠 9000형'
        - '[DTS] 한큐전철 6000형'
        - '[DTS] 한큐전철 6300형'
        - '[DTS] 한큐전철 8000형'
        - '[DTS] 한큐전철 8300형'
        - '[DTS] 한큐전철 8300형'
        - '[DTS] 한큐전철 9000형'
        - '[DTS] 한큐전철 9300형'
        - '[DTS/8량] 케이세이 AE형 2세대'
        - '[DTS] 신칸센 0계'
        - '[DTS] 신칸센 700계'
        - '[DTS/6량] 신칸센 800계'
        - '[DTS/10량] 신칸센 E2계'
        - '[DTS/12량] 신칸센 E7·W7계'
        - '[DTS] 신칸센 500계'
        - '[DTS] 신칸센 N700계'
        - '[DTS] 신칸센 N700S계'
        - '[DTS/10량] 신칸센 E5·H5계'
        - '[DTS/7량] 신칸센 E6계'
        - '[DTS/7량] 신칸센 E8계'
        - '[DTS/7량] 신칸센 923형 (닥터 옐로우)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 버그사항
      description: 문제가 발생한 버그사항. 필요시 스샷 첨부
    validations:
      required: true
  - type: textarea
    attributes:
      label: 개선점
      description: 개선될 사항을 알려주세요.
    validations:
      required: true