name: "[열차변경] 유럽형 열차"
description: DTS의 유럽형 열차 그래픽을 바꾸고 싶으십니까?
title: "[열차변경]"
labels: Edit Graphic
body:
  - type: markdown
    attributes:
      value: |
        변경사항을 추가해주셔서 감사합니다!
  - type: dropdown
    attributes:
      label: 유럽형 열차 선택
      description: 유럽형 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/단량] SNCF BB15000'
        - '[DTS/14량] ICE1'
        - '[DTS/8량] ICE2'
        - '[DTS] ICE4 (그룹)'
        - '[DTS/7량] ICE4'
        - '[DTS/12량] ICE4'
        - '[DTS/13량] 렌페 S-130'
        - '[DTS/11량] AGV (이탈로)'
        - '[DTS/20량] 유로스타 E300'
        - '[DTS/16량] 유로스타 E320'
        - '[DTS/8량] ICE3'
        - '[DTS/8량] ICE3 (벨라로 D)'
        - '[DTS/10량] 렌페 AVE S-100'
        - '[DTS/14량] 렌페 AVE S-102'
        - '[DTS/8량] 렌페 AVE S-103'
        - '[DTS/10량] TGV 듀플렉스'
        - '[DTS/10량] TGV 포스'
        - '[DTS/10량] TGV 쉬드-에스트'
        - '[DTS/10량] TGV 레조 듀플렉스'
        - '[DTS/12량] TGV 아틀랑티크'
        - '[DTS/10량] TGV 레조'
        - '[DTS/10량] TGV 라포스트'
        - '[DTS/10량] TGV M'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 변경 스프라이트
      description: 변경될 스프라이트를 올려주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 설명
      description: 설명사항을 적어주세요.
  - type: textarea
    attributes:
      label: 적용내용
      description: 변경될 사항을 적어주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 편성구조
      description: 편성 구조가 변경되면 적어주세요.