name: "[열차변경]"
description: DTS의 열차 그래픽을 바꾸고 싶으십니까?
title: "[열차변경]"
labels: "Edit Graphic"
body:
  - type: input
    id: In_Game_name
    attributes:
      label: In_Game_name
      description: 게임에서 나오는 해당 열차 이름을 적어주세요.
      placeholder: '[DTS/N량] 열차이름'
    validations:
      required: true