name: "[열차변경] 객화차형 열차"
description: DTS의 객화차형 열차 그래픽을 바꾸고 싶으십니까?
title: "[열차변경]"
labels: Edit Graphic
body:
  - type: markdown
    attributes:
      value: |
        변경사항을 추가해주셔서 감사합니다!
  - type: dropdown
    attributes:
      label: 객화차 선택
      description: 객화차에 해당하면 선택해주세요.
      options:
        - '[DTS] 관광열차'
        - '[DTS/기관차연결] 가상 객차 차량'
        - '[DTS/기관차연결] 한국 무궁화호 객차 차량'
        - '[DTS/기관차연결] 한국 새마을호 객차 차량'
        - '[DTS/기관차연결] 중국 객차 차량'
        - '[DTS/기관차연결] 유럽 객차 차량'
        - '[DTS/기관차연결] 한국 발전차'
        - '[DTS/기관차연결] 중국 발전차'
        - '[DTS/기관차연결] 한국 수화물차'
        - '[DTS/기관차연결] 중국 수화물차'
        - '[DTS/기관차연결] 평판화차'
        - '[DTS/기관차연결] 평판유조 화차'
        - '[DTS/기관차연결] 평판화차 - 미국형'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 변경 스프라이트
      description: 변경될 스프라이트를 올려주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 설명
      description: 설명사항을 적어주세요.
  - type: textarea
    attributes:
      label: 적용내용
      description: 변경될 사항을 적어주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 편성구조
      description: 편성 구조가 변경되면 적어주세요.