name: "[열차변경] 월드형 열차"
description: DTS의 월드형 열차 그래픽을 바꾸고 싶으십니까?
title: "[열차변경]"
labels: Edit Graphic
body:
  - type: markdown
    attributes:
      value: |
        변경사항을 추가해주셔서 감사합니다!
  - type: dropdown
    attributes:
      label: 월드형 열차 선택
      description: 월드형 열차에 해당하면 선택해주세요.
      options:
        - '[DTS] NSW TrainLink D (그룹)'
        - '[DTS/4량] NSW TrainLink D'
        - '[DTS/6량] NSW TrainLink D'
        - '[DTS/10량] NHSRCL E5'
        - '[DTS/12량] 타이완 고속철도 700T형'
        - '[DTS/10량] 알 보라크'
        - '[DTS/14량] 탈고 350 SRO (하라마인 고속철도)'
        - '[DTS/11량] 아벨리아 리버티'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 변경 스프라이트
      description: 변경될 스프라이트를 올려주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 설명
      description: 설명사항을 적어주세요.
  - type: textarea
    attributes:
      label: 적용내용
      description: 변경될 사항을 적어주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 편성구조
      description: 편성 구조가 변경되면 적어주세요.