name: "[열차변경] 기본형 열차"
description: DTS의 기본형 열차 그래픽을 바꾸고 싶으십니까?
title: "[열차변경]"
labels: Edit Graphic
body:
  - type: markdown
    attributes:
      value: |
        변경사항을 추가해주셔서 감사합니다!
  - type: dropdown
    attributes:
      label: 기본 열차 선택
      description: 기본 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/4량] 한국형 표준전동차'
        - '[DTS/6량] 차세대전동차'
        - '[DTS] 한국철도공사 1세대 VVVF 전동차'
        - '[DTS] 서울교통공사 1세대 VVVF 전동차'
        - '[DTS] 한국철도공사 2세대 VVVF 전동차'
        - '[DTS] 서울교통공사 2세대 VVVF 전동차'
        - '[DTS] 한국철도공사 3세대 VVVF 전동차'
        - '[DTS] 서울교통공사 3세대 VVVF 전동차'
        - '[DTS] 한국철도공사 4세대 VVVF 전동차'
        - '[DTS] 서울교통공사 4세대 VVVF 전동차'
        - '[DTS/10량] 한국철도공사 5세대 VVVF 전동차'
        - '[DTS] 수도권 1호선 저항제어 전동차'
        - '[DTS] 서울교통공사 2000호대 저항제어 전동차'
        - '[DTS] 서울교통공사 2000호대 멜코초퍼'
        - '[DTS] 서울교통공사 2000호대 GEC초퍼'
        - '[DTS] 서울교통공사 광폭형 GEC초퍼'
        - '[DTS] 우진산전 수소연료전지동차'
        - '[DTS/6량] AREX (공항철도)'
        - '[DTS] MEL-150'
        - '[DTS] CL-150'
        - '[DTS] 비츠로'
        - '[DTS/6량] 비츠로 DD'
        - '[DTS/4량] 누리로 DD'
        - '[DTS/6량] ITX-새마을 DD'
        - '[DTS/단량] 7X00호대 디젤기관차'
        - '[DTS/단량] DEL7000'
        - '[DTS/단량] DEL7600'
        - '[DTS/단량] 8100호대 전기기관차'
        - '[DTS/단량] 8200호대 전기기관차'
        - '[DTS/단량] 8500호대 전기기관차'
        - '[DTS/단량] 8600호대 전기기관차'
        - '[DTS/단량] HYEL-15'
        - '[DTS/단량] HYEL-100'
        - '[DTS] HYEL-200'
        - '[DTS/6량] HYEL-220'
        - '[DTS/8량] NKX'
        - '[DTS/8량] GTX'
        - '[DTS/8량] ITX-초월'
        - '[DTS/6량] TTX'
        - '[DTS/6량] EMU-260'
        - '[DTS/6량] EMU-260 DD'
        - '[DTS/단량] HYEL-150'
        - '[DTS/8량] HYEL-300'
        - '[DTS/8량] HMX'
        - '[DTS/8량] EMU-320'
        - '[DTS/8량] EMU-320 DD'
        - '[DTS/10량] KTX-산천'
        - '[DTS/10량] KTX-산천 DD'
        - '[DTS] CTX'
        - '[DTS] HSR-350X'
        - '[DTS] HEMU-430X'
        - '[DTS/8량] HYEL-400'
        - '[DTS/8량] VHST-600X'
        - '[DTS/8량] Glory 600'
        - '[DTS/10량] DFX'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 변경 스프라이트
      description: 변경될 스프라이트를 올려주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 설명
      description: 설명사항을 적어주세요.
  - type: textarea
    attributes:
      label: 적용내용
      description: 변경될 사항을 적어주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 편성구조
      description: 편성 구조가 변경되면 적어주세요.