name: "[열차변경]"
description: DTS의 열차 그래픽을 바꾸고 싶으십니까?
title: "[열차변경]"
labels: Edit Graphic
body:
  - type: markdown
    attributes:
      value: |
        변경사항을 추가해주셔서 감사합니다!
  - type: dropdown
    attributes:
      label: 기본 열차 선택
      description: 기본 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/4량] 한국형 표준전동차'
        - '[DTS/6량] 차세대전동차'
        - '[DTS] 한국철도공사 1세대 VVVF 전동차 (그룹)'
        - '[DTS/4량] 한국철도공사 1세대 319K IGBT'
        - '[DTS/4량] 한국철도공사 1세대 319K GTO'
        - '[DTS/6량] 한국철도공사 1세대 3X1K'
        - '[DTS/6량] 한국철도공사 1세대 3X1K, 2030'
        - '[DTS/10량] 한국철도공사 1세대 3X1K'
        - '[DTS/10량] 한국철도공사 1세대 3X1K, 2030, 5000'
        - '[DTS] 한국철도공사 2세대 VVVF 전동차 (그룹)'
        - '[DTS/6량] 한국철도공사 2세대 IGBT'
        - '[DTS/6량] 한국철도공사 2세대 GTO'
        - '[DTS/10량] 한국철도공사 2세대 IGBT'
        - '[DTS/10량] 한국철도공사 2세대 GTO'
        - '[DTS] 한국철도공사 3세대 VVVF 전동차 (그룹)'
        - '[DTS/4량] 한국철도공사 3세대 1차 도입분'
        - '[DTS/4량] 한국철도공사 3세대 2차 도입분'
        - '[DTS/6량] 한국철도공사 3세대 전동차'
        - '[DTS/8량] 한국철도공사 3세대 전동차'
        - '[DTS/10량] 한국철도공사 3세대 전동차'
        - '[DTS] 한국철도공사 4세대 VVVF 전동차 (그룹)'
        - '[DTS/2량] 한국철도공사 392000호대 전동차'
        - '[DTS/4량] 한국철도공사 392000호대 전동차'
        - '[DTS/4량] 한국철도공사 4세대 초기도입분'
        - '[DTS/4량] 한국철도공사 4세대 1·2차 도입분'
        - '[DTS/6량] 한국철도공사 4세대 1·2차 도입분'
        - '[DTS/10량] 한국철도공사 4세대 1·2차 도입분'
        - '[DTS/10량] 한국철도공사 5세대 VVVF 전동차'
        - '[DTS] 수도권 1호선 저항제어 전동차 (그룹)'
        - '[DTS/4량] 수도권 1호선 저항제어 전동차'
        - '[DTS/6량] 수도권 1호선 저항제어 전동차'
        - '[DTS/8량] 수도권 1호선 저항제어 전동차'
        - '[DTS/10량] 수도권 1호선 저항제어 전동차'
        - '[DTS] 우진산전 수소연료전지동차 (열차그룹)'
        - '[DTS/2량] 우진산전 수소연료전지동차'
        - '[DTS/4량] 우진산전 수소연료전지동차'
        - '[DTS/6량] AREX (공항철도)'
        - '[DTS] MEL-150 (열차그룹)'
        - '[DTS/4량] MEL-150'
        - '[DTS/8량] MEL-150'
        - '[DTS/10량] MEL-150'
        - '[DTS/12량] MEL-150'
        - '[DTS] CL-150 (열차그룹)'
        - '[DTS/4량] CL-150'
        - '[DTS/6량] CL-150'
        - '[DTS/8량] CL-150'
        - '[DTS/8량] CL-180'
        - '[DTS] 비츠로 (열차그룹)'
        - '[DTS/4량] 비츠로'
        - '[DTS/6량] 비츠로'
        - '[DTS/8량] 비츠로'
        - '[DTS/6량] 비츠로 DD'
        - '[DTS/4량] 누리로 DD'
        - '[DTS/6량] ITX-새마을 DD'
        - '[DTS/단량] 7X00호대 디젤기관차'
        - '[DTS/단량] DEL7600'
        - '[DTS/단량] 8500호대 전기기관차'
        - '[DTS/단량] 8200호대 전기기관차'
        - '[DTS/단량] 8600호대 전기기관차'
        - '[DTS/단량] HYEL-15'
        - '[DTS/단량] HYEL-100'
        - '[DTS] HYEL-200 (그룹)'
        - '[DTS/4량] HYEL-200'
        - '[DTS/6량] HYEL-200'
        - '[DTS/6량] HYEL-220'
        - '[DTS/8량] NKX'
        - '[DTS/8량] GTX'
        - '[DTS/8량] ITX-초월'
        - '[DTS/6량] TTX'
        - '[DTS/6량] EMU-260'
        - '[DTS/6량] EMU-260 DD'
        - '[DTS/단량] HYEL-150'
        - '[DTS/8량] HYEL-300'
        - '[DTS/8량] HMX'
        - '[DTS/8량] EMU-320'
        - '[DTS/8량] EMU-320 DD'
        - '[DTS/10량] KTX-산천'
        - '[DTS/10량] KTX-산천 DD'
        - '[DTS] CTX (열차그룹)'
        - '[DTS/10량] CTX 화물전용'
        - '[DTS/10량] CTX 승객전용'
        - '[DTS] HSR-350X (열차그룹)'
        - '[DTS/7량] HSR-350X'
        - '[DTS/14량] HSR-350X'
        - '[DTS] HEMU-430X (열차그룹)'
        - '[DTS/6량] HEMU-430X'
        - '[DTS/8량] HEMU-430X'
        - '[DTS/8량] HYEL-400'
        - '[DTS/8량] VHST-600X'
        - '[DTS/8량] Glory 600'
        - '[DTS/10량] DFX'
  - type: dropdown
    attributes:
      label: 중국형 열차 선택
      description: 중국형 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/단량] HXD3C'
        - '[DTS/단량] NJ2'
        - '[DTS/8량] CRH1A'
        - '[DTS/16량] CRH1E'
        - '[DTS/8량] CRH1A-A'
        - '[DTS/8량] CRH2A'
        - '[DTS/16량] CRH2B'
        - '[DTS/8량] CRH2C'
        - '[DTS/8량] CRH3C'
        - '[DTS/8량] CRH380A'
        - '[DTS/16량] CRH380AL'
        - '[DTS/8량] CRH380B'
        - '[DTS/16량] CRH380BL'
        - '[DTS/16량] CRH380CL'
        - '[DTS] CRH380D (그룹)'
        - '[DTS/8량] CRH380D'
        - '[DTS/16량] CRH380D'
        - '[DTS] CR400AF (그룹)'
        - '[DTS/8량] CR400AF'
        - '[DTS/16량] CR400AF'
        - '[DTS/17량] CR400AF'
        - '[DTS] CR400AF-Z (그룹)'
        - '[DTS/8량] CR400AF-Z'
        - '[DTS/17량] CR400AF-Z'
        - '[DTS] CR400BF (그룹)'
        - '[DTS/8량] CR400BF'
        - '[DTS/16량] CR400BF'
        - '[DTS/17량] CR400BF'
        - '[DTS/8량] CR400BF-C'
        - '[DTS] CR400BF-Z (그룹)'
        - '[DTS/8량] CR400BF-Z'
        - '[DTS/17량] CR400BF-Z'
        - '[DTS/8량] CRH380AJ'
  - type: dropdown
    attributes:
      label: 홍콩형 열차 선택
      description: 홍콩형 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/8량] 홍콩 MTR AD Tranz CAF A형'
        - '[DTS/8량] 홍콩 MTR 메트로카멜 교류형 전동차'
        - '[DTS/8량] 홍콩 MTR 메트로카멜 직류형 전동차'
        - '[DTS/8량] 홍콩 MTR CNR 창춘 전동차'
        - '[DTS/8량] 홍콩 MTR CRRC 전동차'
        - '[DTS/8량] 홍콩 MTR 현대로템 미쓰비시 전동차'
        - '[DTS/8량] 홍콩 MTR 현대로템 R형 전동차'
        - '[DTS/8량] 홍콩 MTR IKK SP 1900'
  - type: dropdown
    attributes:
      label: 유럽형 열차 선택
      description: 유럽형 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/단량] SNCF BB15000'
        - '[DTS/14량] ICE1'
        - '[DTS/8량] ICE2'
        - '[DTS] ICE4 (그룹)'
        - '[DTS/7량] ICE4'
        - '[DTS/12량] ICE4'
        - '[DTS/13량] 렌페 S-130'
        - '[DTS/11량] AGV (이탈로)'
        - '[DTS/20량] 유로스타 E300'
        - '[DTS/16량] 유로스타 E320'
        - '[DTS/8량] ICE3'
        - '[DTS/8량] ICE3 (벨라로 D)'
        - '[DTS/10량] 렌페 AVE S-100'
        - '[DTS/14량] 렌페 AVE S-102'
        - '[DTS/8량] 렌페 AVE S-103'
        - '[DTS/10량] TGV 듀플렉스'
        - '[DTS/10량] TGV 포스'
        - '[DTS/10량] TGV 쉬드-에스트'
        - '[DTS/10량] TGV 레조 듀플렉스'
        - '[DTS/12량] TGV 아틀랑티크'
        - '[DTS/10량] TGV 레조'
        - '[DTS/10량] TGV 라포스트'
        - '[DTS/10량] TGV M'
  - type: dropdown
    attributes:
      label: 일본형 열차 선택
      description: 일본형 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/4량] 니시테츠 1000형'
        - '[DTS/6량] 니시테츠 2000형'
        - '[DTS] 니시테츠 3000형 (그룹)'
        - '[DTS/2량] 니시테츠 3000형'
        - '[DTS/3량] 니시테츠 3000형'
        - '[DTS/5량] 니시테츠 3000형'
        - '[DTS] 니시테츠 5000형 (그룹)'
        - '[DTS/3량] 니시테츠 5000형'
        - '[DTS/4량] 니시테츠 5000형'
        - '[DTS] 니시테츠 6000형 (그룹)'
        - '[DTS/3량] 니시테츠 6000형'
        - '[DTS/4량] 니시테츠 6000형'
        - '[DTS/3량] 니시테츠 6050형'
        - '[DTS/4량] 니시테츠 6050형'
        - '[DTS/2량] 니시테츠 7000형'
        - '[DTS/6량] 니시테츠 8000형'
        - '[DTS] 니시테츠 9000형 (그룹)'
        - '[DTS/2량] 니시테츠 9000형'
        - '[DTS/3량] 니시테츠 9000형'
        - '[DTS] 한큐전철 6000형 (그룹)'
        - '[DTS/2량] 한큐전철 6000형'
        - '[DTS/3량] 한큐전철 6000형'
        - '[DTS/4량] 한큐전철 6000형'
        - '[DTS/8량] 한큐전철 6000형'
        - '[DTS] 한큐전철 6300형 (그룹)'
        - '[DTS/4량] 한큐전철 6300형'
        - '[DTS/8량] 한큐전철 6300형'
        - '[DTS] 한큐전철 8000형 (그룹)'
        - '[DTS/2량] 한큐전철 8000형'
        - '[DTS/8량] 한큐전철 8000형'
        - '[DTS] 한큐전철 8300형 (그룹)'
        - '[DTS/2량] 한큐전철 8300형'
        - '[DTS/8량] 한큐전철 8300형'
        - '[DTS/8량] 케이세이 AE형 2세대'
        - '[DTS] 신칸센 0계 (그룹)'
        - '[DTS/12량] 신칸센 0계'
        - '[DTS/16량] 신칸센 0계'
        - '[DTS] 신칸센 700계 (그룹)'
        - '[DTS/8량] 신칸센 700계 레일스타'
        - '[DTS/16량] 신칸센 700계'
        - '[DTS/6량] 신칸센 800계'
        - '[DTS/10량] 신칸센 E2계'
        - '[DTS/12량] 신칸센 E7·W7계'
        - '[DTS] 신칸센 500계 (그룹)'
        - '[DTS/8량] 신칸센 500계'
        - '[DTS/16량] 신칸센 500계'
        - '[DTS] 신칸센 N700계 (그룹)'
        - '[DTS/8량] 신칸센 N700계 큐슈'
        - '[DTS/16량] 신칸센 N700계'
        - '[DTS] 신칸센 N700S계 (그룹)'
        - '[DTS/6량] 신칸센 N700S계 니시큐슈'
        - '[DTS/16량] 신칸센 N700S계'
        - '[DTS/10량] 신칸센 E5·H5계'
        - '[DTS/7량] 신칸센 E6계'
        - '[DTS/7량] 신칸센 E8계'
        - '[DTS/7량] 신칸센 923형 (닥터 옐로우)'
  - type: dropdown
    attributes:
      label: 월드형 열차 선택
      description: 월드형 열차에 해당하면 선택해주세요.
      options:
        - '[DTS] NSW TrainLink D (그룹)'
        - '[DTS/4량] NSW TrainLink D'
        - '[DTS/6량] NSW TrainLink D'
        - '[DTS/10량] NHSRCL E5'
        - '[DTS/12량] 타이완 고속철도 700T형'
        - '[DTS/10량] 알 보라크'
        - '[DTS/14량] 탈고 350 SRO (하라마인 고속철도)'
        - '[DTS/11량] 아벨리아 리버티'
  - type: dropdown
    attributes:
      label: 유지보수형 열차 선택
      description: 유지보수 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/단량] MSB 모터카'
  - type: dropdown
    attributes:
      label: 객화차 선택
      description: 객화차에 해당하면 선택해주세요.
      options:
        - '[DTS] 관광열차 (그룹)'
        - '[DTS/관광객차] 에코레일'
        - '[DTS/관광객차] 충북영동국악와인'
        - '[DTS/관광객차] 정선아리랑 유람열차'
        - '[DTS/관광객차] E-Train'
        - '[DTS/관광객차] 와인인삼트레인'
        - '[DTS/관광객차] 와인시네마트레인'
        - '[DTS/관광객차] 레이디버드'
        - '[DTS/관광객차] S-Train 신도색'
        - '[DTS/관광객차] A-Train 신도색'
        - '[DTS/관광객차] G-Train 신도색'
        - '[DTS/기관차연결] 가상 객차 차량'
        - '[DTS/기관차연결] 한국 무궁화호 객차 차량'
        - '[DTS/기관차연결] 한국 새마을호 객차 차량'
        - '[DTS/기관차연결] 중국 객차 차량'
        - '[DTS/기관차연결] 유럽 객차 차량'
        - '[DTS/기관차연결] 한국 발전차'
        - '[DTS/기관차연결] 중국 발전차'
        - '[DTS/기관차연결] 한국 수화물차'
        - '[DTS/기관차연결] 중국 수화물차'
        - '[DTS/기관차연결] 평판화차'
        - '[DTS/기관차연결] 평판유조 화차'
        - '[DTS/기관차연결] 평판화차 - 미국형'
  - type: textarea
    attributes:
      label: 변경 스프라이트
      description: 변경될 스프라이트를 올려주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 설명
      description: 설명사항을 적어주세요.
  - type: textarea
    attributes:
      label: 적용내용
      description: 변경될 사항을 적어주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 편성구조
      description: 편성 구조가 변경되면 적어주세요.