name: "[열차변경]"
description: DTS의 열차 그래픽을 바꾸고 싶으십니까?
title: "[열차변경]"
labels: Edit_Graphic
body:
  - type: markdown
    attributes:
      value: |
        열차 변경을 작성해주셔서 감사합니다!
  - type: input
    attributes:
      label: Train_name
      description: 게임에서 나오는 해당 열차 이름을 적어주세요.
      placeholder: '[DTS/N량] 열차이름'
    validations:
      required: true