name: "[열차변경] 일본형 열차"
description: DTS의 일본형 열차 그래픽을 바꾸고 싶으십니까?
title: "[열차변경]"
labels: Edit Graphic
body:
  - type: markdown
    attributes:
      value: |
        변경사항을 추가해주셔서 감사합니다!
  - type: dropdown
    attributes:
      label: 일본형 열차 선택
      description: 일본형 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/4량] 니시테츠 1000형'
        - '[DTS/6량] 니시테츠 2000형'
        - '[DTS] 니시테츠 3000형 (그룹)'
        - '[DTS/2량] 니시테츠 3000형'
        - '[DTS/3량] 니시테츠 3000형'
        - '[DTS/5량] 니시테츠 3000형'
        - '[DTS] 니시테츠 5000형 (그룹)'
        - '[DTS/3량] 니시테츠 5000형'
        - '[DTS/4량] 니시테츠 5000형'
        - '[DTS] 니시테츠 6000형 (그룹)'
        - '[DTS/3량] 니시테츠 6000형'
        - '[DTS/4량] 니시테츠 6000형'
        - '[DTS/3량] 니시테츠 6050형'
        - '[DTS/4량] 니시테츠 6050형'
        - '[DTS/2량] 니시테츠 7000형'
        - '[DTS/6량] 니시테츠 8000형'
        - '[DTS] 니시테츠 9000형 (그룹)'
        - '[DTS/2량] 니시테츠 9000형'
        - '[DTS/3량] 니시테츠 9000형'
        - '[DTS] 한큐전철 6000형 (그룹)'
        - '[DTS/2량] 한큐전철 6000형'
        - '[DTS/3량] 한큐전철 6000형'
        - '[DTS/4량] 한큐전철 6000형'
        - '[DTS/8량] 한큐전철 6000형'
        - '[DTS] 한큐전철 6300형 (그룹)'
        - '[DTS/4량] 한큐전철 6300형'
        - '[DTS/8량] 한큐전철 6300형'
        - '[DTS] 한큐전철 8000형 (그룹)'
        - '[DTS/2량] 한큐전철 8000형'
        - '[DTS/8량] 한큐전철 8000형'
        - '[DTS] 한큐전철 8300형 (그룹)'
        - '[DTS/2량] 한큐전철 8300형'
        - '[DTS/8량] 한큐전철 8300형'
        - '[DTS/8량] 한큐전철 9000형'
        - '[DTS/8량] 한큐전철 9300형'
        - '[DTS/8량] 케이세이 AE형 2세대'
        - '[DTS] 신칸센 0계 (그룹)'
        - '[DTS/12량] 신칸센 0계'
        - '[DTS/16량] 신칸센 0계'
        - '[DTS] 신칸센 700계 (그룹)'
        - '[DTS/8량] 신칸센 700계 레일스타'
        - '[DTS/16량] 신칸센 700계'
        - '[DTS/6량] 신칸센 800계'
        - '[DTS/10량] 신칸센 E2계'
        - '[DTS/12량] 신칸센 E7·W7계'
        - '[DTS] 신칸센 500계 (그룹)'
        - '[DTS/8량] 신칸센 500계'
        - '[DTS/16량] 신칸센 500계'
        - '[DTS] 신칸센 N700계 (그룹)'
        - '[DTS/8량] 신칸센 N700계 큐슈'
        - '[DTS/16량] 신칸센 N700계'
        - '[DTS] 신칸센 N700S계 (그룹)'
        - '[DTS/6량] 신칸센 N700S계 니시큐슈'
        - '[DTS/16량] 신칸센 N700S계'
        - '[DTS/10량] 신칸센 E5·H5계'
        - '[DTS/7량] 신칸센 E6계'
        - '[DTS/7량] 신칸센 E8계'
        - '[DTS/7량] 신칸센 923형 (닥터 옐로우)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 변경 스프라이트
      description: 변경될 스프라이트를 올려주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 설명
      description: 설명사항을 적어주세요.
  - type: textarea
    attributes:
      label: 적용내용
      description: 변경될 사항을 적어주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 편성구조
      description: 편성 구조가 변경되면 적어주세요.