name: "[열차변경] 홍콩형 열차"
description: DTS의 홍콩형 열차 그래픽을 바꾸고 싶으십니까?
title: "[열차변경]"
labels: Edit Graphic
body:
  - type: markdown
    attributes:
      value: |
        변경사항을 추가해주셔서 감사합니다!
  - type: dropdown
    attributes:
      label: 홍콩형 열차 선택
      description: 홍콩형 열차에 해당하면 선택해주세요.
      options:
        - '[DTS/8량] 홍콩 MTR AD Tranz CAF A형'
        - '[DTS/8량] 홍콩 MTR 메트로카멜 교류형 전동차'
        - '[DTS/8량] 홍콩 MTR 메트로카멜 직류형 전동차'
        - '[DTS/8량] 홍콩 MTR CNR 창춘 전동차'
        - '[DTS/8량] 홍콩 MTR CRRC 전동차'
        - '[DTS/8량] 홍콩 MTR 현대로템 미쓰비시 전동차'
        - '[DTS/8량] 홍콩 MTR 현대로템 R형 전동차'
        - '[DTS/8량] 홍콩 MTR IKK SP 1900'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 변경 스프라이트
      description: 변경될 스프라이트를 올려주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 설명
      description: 설명사항을 적어주세요.
  - type: textarea
    attributes:
      label: 적용내용
      description: 변경될 사항을 적어주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 편성구조
      description: 편성 구조가 변경되면 적어주세요.