name: "[열차변경]"
description: DTS의 열차 그래픽을 바꾸고 싶으십니까?
title: "[열차변경]"
labels: Edit_Graphic
body:
  - type: markdown
    attributes:
      value: |
        버그사항 접수해주셔서 감사합니다.!
  - type: dropdown
    attributes:
      label: 열차이름
      description: 변경될 열차를 선택해주세요.
      options:
        - [DTS/6량] AREX (공항철도)
        - [DTS] MEL-150
        - [DTS/4량] MEL-150
        - [DTS/8량] MEL-150
        - [DTS/10량] MEL-150
        - [DTS/12량] MEL-150
        - [DTS] CL-150
        - [DTS/4량] CL-150
        - [DTS/6량] CL-150
        - [DTS/8량] CL-150
        - [DTS/8량] CL-180
        - [DTS] CTX
        - [DTS/10량] CTX 화물전용
        - [DTS/10량] CTX 승객전용
        - [DTS/단량] DEL7600
    validations:
      required: true
  - type: textarea
    attributes:
      label: 변경 스프라이트
      description: 변경될 스프라이트를 올려주세요.
    validations:
      required: true